### ISSUE TITLE
WindowsError: [Error -2147221163] Interface not registered

### ISSUE THREAD

**Issue by Peck117** [WhereGroup/mapqonverter#28]
Hi there, 

I am trying to use the toolbox but get the error below. I am a complete novice when it comes to python but I think the comtypes are correct. Using ArcGIS 10.6 and comtypes 1.1.7 

Any help would be very much appreciated. 

Traceback (most recent call last):
  File "C:\Users\peckc\OneDrive - University of Manitoba\Documents\ArcGIS 10.6\mapqonverter-master\mapqonverter.py", line 159, in <module>
    main()
  File "C:\Users\peckc\OneDrive - University of Manitoba\Documents\ArcGIS 10.6\mapqonverter-master\mapqonverter.py", line 48, in main
    arc_app = CreateObject(ArcGisModules.module_framework.AppROT, interface=ArcGisModules.module_framework.IAppROT)
  File "C:\Python27\ArcGIS10.6\lib\site-packages\comtypes\client\__init__.py", line 238, in CreateObject
    obj = comtypes.CoCreateInstance(clsid, clsctx=clsctx, interface=interface)
  File "C:\Python27\ArcGIS10.6\lib\site-packages\comtypes\__init__.py", line 1227, in CoCreateInstance
    _ole32.CoCreateInstance(byref(clsid), punkouter, clsctx, byref(iid), byref(p))
  File "_ctypes/callproc.c", line 950, in GetResult
WindowsError: [Error -2147221163] Interface not registered

Failed to execute (Mapqonverter).

**Comment by pheidelb** [comment]
Hi Peck117,

if the interface is not registered, somehow comtypes can't load the arcmap libraries. 
There can be many reasons for that. The path looks allright: C:\Python27\ArcGIS10.6\lib\site-packages\comtypes

Unfortunately it's hard to tell, where the problem lies. You can try installing mapqonverter with this setup: https://files.wheregroup.com/s/ksCiBk3SWcMBxsf

Perhaps this helps.

Greetings

Peter
