### ISSUE TITLE
Absturz bei Umlaut in Dateipfad

### ISSUE THREAD

**Issue by Meibes** [WhereGroup/mapqonverter#7]
Skript Mapqonverter wird ausgeführt...
Failed script Mapqonverter...

Traceback (most recent call last):
  File "D:\temp\mapqonverter-master\mapqonverter.py", line 154, in <module>
    main()
  File "D:\temp\mapqonverter-master\mapqonverter.py", line 35, in main
    qgs_file_name = "{}.qgs".format(export_name_short)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xe4' in position 9: ordinal not in range(128)

Fehler beim Ausführen von (Mapqonverter).

**Comment by pheidelb** [comment]
Ah, Danke. Diesen Bug kann ich reproduzieren. Wird zeitnah gehotfixt.
